env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  array-bracket-spacing:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  object-curly-spacing:
    - error
    - always
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/jsx-uses-vars:
    - 1
