/* eslint-disable import/prefer-default-export */

export const DENPAIO_BACKGROUND_IMAGE_UPDATE = 'DENPAIO_BACKGROUND_IMAGE_UPDATE';
export const DENPAIO_PLAY_RELOAD = 'DENPAIO_PLAY_RELOAD';
export const DENPAIO_PLAY_CREATE = 'DENPAIO_PLAY_CREATE';
export const DENPAIO_PLAY_UPDATE = 'DENPAIO_PLAY_UPDATE';
export const DENPAIO_PLAY_DESTROY = 'DENPAIO_PLAY_DESTROY';
