# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69057b900593869d60af7a9c4b4ecc072c3de04d6888e3028d8c9dfde6160f605962ef6833cc6e26adb2725bc8f32e5ded3c7844c2544115d561d7bebb101dac
  auth0_domain: https://denpaio-dev.auth0.com/

test:
  secret_key_base: d7557b3ef12664ee24b1bff6cff93c2bda2e6ceb9b06bb07906ef948a0faaa7419248c607f05e0326210bb359cede8769bce77709af57910c616f297d0a98320
  auth0_domain: https://denpaio-dev.auth0.com/

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth0_domain: https://denpaio.auth0.com/
